### ISSUE TITLE
Add doc search support

### ISSUE THREAD

**Issue by fsismondi** [kameshsampath/antora-site-action#4]
Thanks for sharing antora-site-action

I wonder if you are interested in extending the component to support [Mogztter/antora-lunr](https://github.com/Mogztter/antora-lunr). I would happily contribute to this. 

A proposal for the `action` specification:

```
name: "Antora Site"
description: "Generate the Antora site"
branding:
  icon: book-open
  color: yellow
inputs:
  antora_playbook:
    description: 'The Antora playbook file'
    required: true
    default: 'site.yaml'
  site_sources_path:
    description: 'The path relative to workspace root, where the asciidoc sources exits'
    required: false
  antora_generator:
    description: 'Select generator to be used. Supports "@antora/site-generator-default" or "antora-site-generator-lunr"'
    required: false
    default: '@antora/site-generator-default'
  antora_search_bar_enabled:
    description: 'Select whether to enable the search bar for documentation'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.antora_playbook}}
     - ${{ inputs.site_sources_path }}
     - ${{ inputs.antora_generator }}
     - ${{ inputs.antora_search_bar_enabled }}
```

Happy to provide a PR if you find this reasonable.

Thanks again,
Fede
